### ISSUE TITLE
Unread Count as "Scrolled to count"

### ISSUE THREAD

**Issue by ianrenton** [haku/Onosendai#146]
I've noticed this today since the fix for #51, but it may be older.  When you pull down the left-side menu that lists the columns and their unread count, the count isn't based on unread count (blue scroll bar) but on the number of items above the current view position in that column (blue+grey scroll bar).

Apologies if this is the intended behaviour!

**Comment by haku** [comment]
It is sort of intentional... I never really made my mind up, so left it working the way I found most useful.
I can leave a column scrolled to a certain point as a reminder to go back to something.
The GoTo menu is a lazy hack though and I have been pondering alternatives.
The icon in the top left is not a permanent feature.  I just had enough of code for one weekend.
I was pondering a sort of bar-chart thing in the corner that reproduced the colours from all the scroll bars.
(but I do need to do something about this coding addiction :( )

**Comment by ianrenton** [comment]
Fair enough! With the number of commit emails I've had recently, I think you do need a break from coding :)
